[package]
name = "priority-queue"
version = "0.4.1"
authors = ["Gianmarco Garrisi <gianmarcogarrisi@tutanota.com>"]
description = "A Priority Queue implemented as a heap with a function to efficiently change the priority of an item."
repository = "https://github.com/garro95/priority-queue"
#readme = "README.rst"
keywords = ["priority", "queue", "heap"]
categories = ["data-structures", "algorithms"]
license = "LGPL-3.0"

[badges]
travis-ci = { repository = "garro95/priority-queue", branch = "master" }

[dependencies]
ordermap = "0.3.*"
serde = {version = "1", optional = true}

[dev-dependencies]
serde_test = "1"