name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  TARGET: thumbv6m-none-eabi

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build with serde
      run: cargo build --verbose --features serde
    - name: Run tests with serde
      run: cargo test --verbose --features serde
    - name: Build for no-std
      run: cargo build -v -p test-nostd --target=$TARGET
